#!/usr/bin/env bash
#
# Build AlexaCart.app — a macOS app bundle that starts the server and opens a browser.
# Usage: bash scripts/build_macos_app.sh
#
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
APP_DIR="$PROJECT_DIR/AlexaCart.app"

# ---------------------------------------------------------------------------
# Locate uv
# ---------------------------------------------------------------------------
UV_BIN=""
for candidate in \
    "$HOME/.local/bin/uv" \
    "$HOME/.cargo/bin/uv" \
    "/opt/homebrew/bin/uv" \
    "/usr/local/bin/uv"; do
    if [[ -x "$candidate" ]]; then
        UV_BIN="$candidate"
        break
    fi
done

if [[ -z "$UV_BIN" ]]; then
    echo "Error: could not find uv. Install it first: https://docs.astral.sh/uv/"
    exit 1
fi

UV_DIR="$(dirname "$UV_BIN")"
echo "Found uv at $UV_BIN"

# ---------------------------------------------------------------------------
# Create .app bundle structure
# ---------------------------------------------------------------------------
rm -rf "$APP_DIR"
mkdir -p "$APP_DIR/Contents/MacOS"

# ---------------------------------------------------------------------------
# Info.plist
# ---------------------------------------------------------------------------
cat > "$APP_DIR/Contents/Info.plist" << 'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>AlexaCart</string>
    <key>CFBundleExecutable</key>
    <string>AlexaCart</string>
    <key>CFBundleIdentifier</key>
    <string>com.alexacart.launcher</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>LSUIElement</key>
    <false/>
</dict>
</plist>
PLIST

# ---------------------------------------------------------------------------
# Launcher script
# ---------------------------------------------------------------------------
cat > "$APP_DIR/Contents/MacOS/AlexaCart" << LAUNCHER
#!/usr/bin/env bash
#
# AlexaCart launcher — generated by build_macos_app.sh
# Project: $PROJECT_DIR
# uv:     $UV_BIN
#

PROJECT_DIR="$PROJECT_DIR"
PORT=8000
URL="http://127.0.0.1:\$PORT"

export PATH="$UV_DIR:\$PATH"

# If the server is already running, just open the browser and exit.
if curl -s -o /dev/null -w '' "\$URL" 2>/dev/null; then
    open "\$URL"
    exit 0
fi

cd "\$PROJECT_DIR"

# Start the server in the background.
uv run python run.py &
SERVER_PID=\$!

# Clean up on exit.
cleanup() {
    kill "\$SERVER_PID" 2>/dev/null
    wait "\$SERVER_PID" 2>/dev/null
}
trap cleanup SIGTERM SIGINT EXIT

# Wait for the server to become ready (up to 15 seconds).
for i in \$(seq 1 30); do
    if curl -s -o /dev/null -w '' "\$URL" 2>/dev/null; then
        open "\$URL"
        break
    fi
    sleep 0.5
done

# Keep the app alive in the Dock until the server exits.
wait "\$SERVER_PID"
LAUNCHER

chmod +x "$APP_DIR/Contents/MacOS/AlexaCart"

echo ""
echo "Built $APP_DIR"
echo ""
echo "To add to your Dock:"
echo "  1. Open Finder and navigate to: $PROJECT_DIR"
echo "  2. Drag AlexaCart.app to your Dock"
echo "  3. Double-click to launch!"
