#!/usr/bin/env bash
#
# Build AlexaCart.app — a macOS app bundle that starts the server and opens a browser.
# Usage: bash scripts/build_macos_app.sh
#
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
APP_DIR="$PROJECT_DIR/AlexaCart.app"

# ---------------------------------------------------------------------------
# Locate uv
# ---------------------------------------------------------------------------
UV_BIN=""
for candidate in \
    "$HOME/.local/bin/uv" \
    "$HOME/.cargo/bin/uv" \
    "/opt/homebrew/bin/uv" \
    "/usr/local/bin/uv"; do
    if [[ -x "$candidate" ]]; then
        UV_BIN="$candidate"
        break
    fi
done

if [[ -z "$UV_BIN" ]]; then
    echo "Error: could not find uv. Install it first: https://docs.astral.sh/uv/"
    exit 1
fi

UV_DIR="$(dirname "$UV_BIN")"
echo "Found uv at $UV_BIN"

# ---------------------------------------------------------------------------
# Create .app bundle structure
# ---------------------------------------------------------------------------
rm -rf "$APP_DIR"
mkdir -p "$APP_DIR/Contents/MacOS"
mkdir -p "$APP_DIR/Contents/Resources"

# ---------------------------------------------------------------------------
# App icon
# ---------------------------------------------------------------------------
ICNS_SRC="$PROJECT_DIR/scripts/AlexaCart.icns"
if [[ -f "$ICNS_SRC" ]]; then
    cp "$ICNS_SRC" "$APP_DIR/Contents/Resources/AlexaCart.icns"
    echo "Included app icon"
else
    echo "Warning: $ICNS_SRC not found — app will use default icon"
    echo "  Run: uv run --with pillow python scripts/generate_icon.py"
fi

# ---------------------------------------------------------------------------
# Info.plist
# ---------------------------------------------------------------------------
cat > "$APP_DIR/Contents/Info.plist" << 'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>AlexaCart</string>
    <key>CFBundleExecutable</key>
    <string>AlexaCart</string>
    <key>CFBundleIdentifier</key>
    <string>com.alexacart.launcher</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleIconFile</key>
    <string>AlexaCart</string>
    <key>CFBundleVersion</key>
    <string>1.0</string>
    <key>LSUIElement</key>
    <false/>
</dict>
</plist>
PLIST

# ---------------------------------------------------------------------------
# Launcher script
# ---------------------------------------------------------------------------
cat > "$APP_DIR/Contents/MacOS/AlexaCart" << LAUNCHER
#!/usr/bin/env bash
#
# AlexaCart launcher — generated by build_macos_app.sh
# Project: $PROJECT_DIR
# uv:     $UV_BIN
#

PROJECT_DIR="$PROJECT_DIR"
PORT=8000
URL="http://127.0.0.1:\$PORT"
LOG_FILE="\$PROJECT_DIR/data/alexacart.log"

export PATH="$UV_DIR:\$PATH"
export PYTHONUNBUFFERED=1

# Kill any existing server so we always run the latest code.
OLD_PIDS=\$(lsof -ti :\$PORT 2>/dev/null) || true
if [[ -n "\$OLD_PIDS" ]]; then
    echo "\$OLD_PIDS" | xargs kill 2>/dev/null || true
    sleep 1
fi

# Kill orphaned Chrome processes from previous sessions.
for profile in "\$PROJECT_DIR/data/nodriver-amazon" "\$PROJECT_DIR/data/nodriver-instacart"; do
    pids=\$(pgrep -f "\$profile" 2>/dev/null) || true
    if [[ -n "\$pids" ]]; then
        echo "\$pids" | xargs kill -9 2>/dev/null || true
    fi
done

cd "\$PROJECT_DIR"
mkdir -p "\$PROJECT_DIR/data"

# Rotate logs: keep only the previous run.
[[ -f "\$LOG_FILE" ]] && mv -f "\$LOG_FILE" "\$LOG_FILE.1"

# Start the server, logging stdout+stderr to a file.
uv run python run.py >"\$LOG_FILE" 2>&1 &
SERVER_PID=\$!

# Clean up on exit: kill server + any Chrome processes nodriver spawned.
cleanup() {
    kill "\$SERVER_PID" 2>/dev/null
    wait "\$SERVER_PID" 2>/dev/null
    # Kill lingering nodriver Chrome processes by profile directory.
    for profile in "\$PROJECT_DIR/data/nodriver-amazon" "\$PROJECT_DIR/data/nodriver-instacart"; do
        pids=\$(pgrep -f "\$profile" 2>/dev/null) || true
        if [[ -n "\$pids" ]]; then
            echo "\$pids" | xargs kill -9 2>/dev/null || true
        fi
    done
}
trap cleanup SIGTERM SIGINT EXIT

# Wait for the server to become ready (up to 15 seconds).
for i in \$(seq 1 30); do
    if curl -s -o /dev/null -w '' "\$URL" 2>/dev/null; then
        open "\$URL"
        break
    fi
    sleep 0.5
done

# Keep the app alive in the Dock until the server exits.
wait "\$SERVER_PID"
LAUNCHER

chmod +x "$APP_DIR/Contents/MacOS/AlexaCart"

# Remove macOS quarantine flag — without this, Gatekeeper blocks child
# processes (nodriver/Chrome) from launching when the .app is double-clicked.
xattr -cr "$APP_DIR" 2>/dev/null || true

echo ""
echo "Built $APP_DIR"
echo ""
echo "Logs: $PROJECT_DIR/data/alexacart.log"
echo ""
echo "To add to your Dock:"
echo "  1. Open Finder and navigate to: $PROJECT_DIR"
echo "  2. Drag AlexaCart.app to your Dock"
echo "  3. Double-click to launch!"
